version: "3.7"

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  oraclesync:
    restart: always
    network_mode: "bridge"
    image: mes.com/tools/kafka-connect-oracle:1.0.72
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8083:8083
    volumes:
      - /opt/oracle/datasync/config:/home/java-app/config
      - /opt/oracle/datasync/logs:/home/java-app/logs

  zookeeper:
    network_mode: "bridge"
    image: mes.com/library/zookeeper:3.4.13
    privileged: true
    restart: always
    ports:
      - 2181:2181
    volumes:
      - /etc/localtime:/etc/localtime

  kafka:
    network_mode: "bridge"
    image: mes.com/library/kafka:2.13_2.7.0
    environment:
      - JMX_PORT=9999
      - HOST_IP=192.168.223.167
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=192.168.223.167
      - KAFKA_ADVERTISED_PORT=9092
    ports:
      - 9092:9092
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - zookeeper:zookeeper

  kafkaManage:
    network_mode: "bridge"
    image: mes.com/library/kafka-manager:1.3.3.22
    environment:
      - ZK_HOSTS=zookeeper:2181
    ports:
      - 9001:9000
    volumes:
      - /etc/localtime:/etc/localtime
    links:
      - zookeeper:zookeeper
      - kafka:kafka

